spring:
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    database: 0
    jedis:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2
          max-wait: 100
        #password: 我的redis没有密码