spring:
  redis:
    host: 192.168.122.123
    port:
    password:
    timeout:
    database:
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 100

  redis-two:
    host: 192.168.122.124
      port:
      password:
      timeout:
      database:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100