spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/spring-boot-jdbc?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    schema:
      - classpath:department.sql