server:
  port: 8081
spring:
  profiles:
    active: dev
###yml的激活方式，主要使用的是这个---
#文档块的分割。

---
server:
  port: 8083

spring:
  profiles: dev

---
server:
  port: 8084

spring:
  profiles: prod

person:
  name: hello
  age: 11
  boss: false
  birth: 2018/12/12
  maps: {k1:v1,k2:v2}
  lists:
    -list
    -zhzjo
  dogs:
    name: wangwang
    age: 1